import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Weather from "../@types/forecast";
import sg from "../styles/SnapGrid.module.css";
import Summary from "../components/Summary";

const temps = (forecastday: Weather.Forecastday[], day: number): number[] =>
  forecastday[day].hour.map((hour) => hour.temp_c);

const Home: NextPage<Weather.Forecast> = ({
  location,
  current,
  forecast: { forecastday },
}) => {
  const min = Math.min(...temps(forecastday, current.is_day));
  const max = Math.max(...temps(forecastday, current.is_day));

  useEffect(() => {
    const url = new URL(window.location.href);
    if (!url.hash) {
      url.hash = "summary";
      window.location.href = url.toString();
    }
  }, []);

  return (
    <>
      <div className={sg.root}>
        <Head>
          <title>Weather Now</title>
        </Head>
        <section className={sg.cell}>
          <img src="//unsplash.it/251/250" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/250/251" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/252/250" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/250/252" alt="" />
        </section>
        <section id="summary" className={sg.cell}>
          <Summary
            location={location}
            temps={{ temp: current.temp_c, min, max }}
          />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/250/253" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/254/250" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/255/250" alt="" />
        </section>
        <section className={sg.cell}>
          <img src="//unsplash.it/250/255" alt="" />
        </section>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps<Weather.Forecast> = async () => {
  return {
    props: {
      location: {
        name: "Itapuca",
        region: "Rio Grande do Sul",
        country: "Brazil",
        lat: -28.89,
        lon: -52.04,
        tz_id: "America/Sao_Paulo",
        localtime_epoch: 1643573983,
        localtime: "2022-01-30 17:19",
      },
      current: {
        last_updated_epoch: 1643573700,
        last_updated: "2022-01-30 17:15",
        temp_c: 24.6,
        temp_f: 76.3,
        is_day: 1,
        condition: {
          text: "Patchy rain possible",
          icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
          code: 1063,
        },
        wind_mph: 0.2,
        wind_kph: 0.4,
        wind_degree: 161,
        wind_dir: "SSE",
        pressure_mb: 1007.0,
        pressure_in: 29.74,
        precip_mm: 0.1,
        precip_in: 0.0,
        humidity: 63,
        cloud: 81,
        feelslike_c: 26.0,
        feelslike_f: 78.8,
        vis_km: 10.0,
        vis_miles: 6.0,
        uv: 5.0,
        gust_mph: 0.4,
        gust_kph: 0.7,
        air_quality: {
          co: 176.89999389648438,
          no2: 0.6000000238418579,
          o3: 43.29999923706055,
          so2: 0.20000000298023224,
          pm2_5: 0.8999999761581421,
          pm10: 2.4000000953674316,
          "us-epa-index": 1,
          "gb-defra-index": 1,
        },
      },
      forecast: {
        forecastday: [
          {
            date: "2022-01-30",
            date_epoch: 1643500800,
            day: {
              maxtemp_c: 27.7,
              maxtemp_f: 81.9,
              mintemp_c: 15.3,
              mintemp_f: 59.5,
              avgtemp_c: 20.3,
              avgtemp_f: 68.6,
              maxwind_mph: 4.3,
              maxwind_kph: 6.8,
              totalprecip_mm: 2.1,
              totalprecip_in: 0.08,
              avgvis_km: 8.7,
              avgvis_miles: 5.0,
              avghumidity: 77.0,
              daily_will_it_rain: 1,
              daily_chance_of_rain: 88,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              uv: 11.0,
            },
            astro: {
              sunrise: "05:56 AM",
              sunset: "07:25 PM",
              moonrise: "03:47 AM",
              moonset: "06:27 PM",
              moon_phase: "Waning Crescent",
              moon_illumination: "5",
            },
            hour: [
              {
                time_epoch: 1643511600,
                time: "2022-01-30 00:00",
                temp_c: 16.9,
                temp_f: 62.4,
                is_day: 0,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  code: 1003,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 109,
                wind_dir: "ESE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 84,
                cloud: 28,
                feelslike_c: 16.9,
                feelslike_f: 62.4,
                windchill_c: 16.9,
                windchill_f: 62.4,
                heatindex_c: 16.9,
                heatindex_f: 62.4,
                dewpoint_c: 14.1,
                dewpoint_f: 57.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.6,
                gust_kph: 5.8,
                uv: 1.0,
              },
              {
                time_epoch: 1643515200,
                time: "2022-01-30 01:00",
                temp_c: 17.1,
                temp_f: 62.8,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 102,
                wind_dir: "ESE",
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 84,
                cloud: 24,
                feelslike_c: 17.1,
                feelslike_f: 62.8,
                windchill_c: 17.1,
                windchill_f: 62.8,
                heatindex_c: 17.1,
                heatindex_f: 62.8,
                dewpoint_c: 14.3,
                dewpoint_f: 57.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.1,
                gust_kph: 5.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643518800,
                time: "2022-01-30 02:00",
                temp_c: 17.0,
                temp_f: 62.6,
                is_day: 0,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  code: 1003,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 98,
                wind_dir: "E",
                pressure_mb: 1011.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 84,
                cloud: 29,
                feelslike_c: 17.0,
                feelslike_f: 62.6,
                windchill_c: 17.0,
                windchill_f: 62.6,
                heatindex_c: 17.0,
                heatindex_f: 62.6,
                dewpoint_c: 14.3,
                dewpoint_f: 57.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.1,
                gust_kph: 5.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643522400,
                time: "2022-01-30 03:00",
                temp_c: 15.9,
                temp_f: 60.6,
                is_day: 0,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  code: 1003,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 96,
                wind_dir: "E",
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 89,
                cloud: 54,
                feelslike_c: 15.9,
                feelslike_f: 60.6,
                windchill_c: 15.9,
                windchill_f: 60.6,
                heatindex_c: 15.9,
                heatindex_f: 60.6,
                dewpoint_c: 14.1,
                dewpoint_f: 57.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.1,
                gust_kph: 5.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643526000,
                time: "2022-01-30 04:00",
                temp_c: 15.3,
                temp_f: 59.5,
                is_day: 0,
                condition: {
                  text: "Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                  code: 1006,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 89,
                wind_dir: "E",
                pressure_mb: 1012.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 92,
                cloud: 83,
                feelslike_c: 15.3,
                feelslike_f: 59.5,
                windchill_c: 15.3,
                windchill_f: 59.5,
                heatindex_c: 15.3,
                heatindex_f: 59.5,
                dewpoint_c: 14.0,
                dewpoint_f: 57.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.4,
                gust_kph: 5.4,
                uv: 1.0,
              },
              {
                time_epoch: 1643529600,
                time: "2022-01-30 05:00",
                temp_c: 16.5,
                temp_f: 61.7,
                is_day: 0,
                condition: {
                  text: "Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                  code: 1006,
                },
                wind_mph: 1.6,
                wind_kph: 2.5,
                wind_degree: 76,
                wind_dir: "ENE",
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 85,
                cloud: 86,
                feelslike_c: 16.5,
                feelslike_f: 61.7,
                windchill_c: 16.5,
                windchill_f: 61.7,
                heatindex_c: 16.5,
                heatindex_f: 61.7,
                dewpoint_c: 13.9,
                dewpoint_f: 57.0,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.5,
                gust_kph: 4.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643533200,
                time: "2022-01-30 06:00",
                temp_c: 17.3,
                temp_f: 63.1,
                is_day: 1,
                condition: {
                  text: "Overcast",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                  code: 1009,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 69,
                wind_dir: "ENE",
                pressure_mb: 1013.0,
                pressure_in: 29.9,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 82,
                cloud: 100,
                feelslike_c: 17.3,
                feelslike_f: 63.1,
                windchill_c: 17.3,
                windchill_f: 63.1,
                heatindex_c: 17.3,
                heatindex_f: 63.1,
                dewpoint_c: 14.1,
                dewpoint_f: 57.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.5,
                gust_kph: 4.0,
                uv: 4.0,
              },
              {
                time_epoch: 1643536800,
                time: "2022-01-30 07:00",
                temp_c: 18.1,
                temp_f: 64.6,
                is_day: 1,
                condition: {
                  text: "Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                  code: 1006,
                },
                wind_mph: 2.5,
                wind_kph: 4.0,
                wind_degree: 67,
                wind_dir: "ENE",
                pressure_mb: 1013.0,
                pressure_in: 29.91,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 78,
                cloud: 67,
                feelslike_c: 18.1,
                feelslike_f: 64.6,
                windchill_c: 18.1,
                windchill_f: 64.6,
                heatindex_c: 18.1,
                heatindex_f: 64.6,
                dewpoint_c: 14.2,
                dewpoint_f: 57.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.4,
                gust_kph: 5.4,
                uv: 4.0,
              },
              {
                time_epoch: 1643540400,
                time: "2022-01-30 08:00",
                temp_c: 19.1,
                temp_f: 66.4,
                is_day: 1,
                condition: {
                  text: "Overcast",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                  code: 1009,
                },
                wind_mph: 2.9,
                wind_kph: 4.7,
                wind_degree: 64,
                wind_dir: "ENE",
                pressure_mb: 1013.0,
                pressure_in: 29.91,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 75,
                cloud: 94,
                feelslike_c: 19.1,
                feelslike_f: 66.4,
                windchill_c: 19.1,
                windchill_f: 66.4,
                heatindex_c: 19.1,
                heatindex_f: 66.4,
                dewpoint_c: 14.6,
                dewpoint_f: 58.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.6,
                gust_kph: 5.8,
                uv: 4.0,
              },
              {
                time_epoch: 1643544000,
                time: "2022-01-30 09:00",
                temp_c: 21.6,
                temp_f: 70.9,
                is_day: 1,
                condition: {
                  text: "Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                  code: 1006,
                },
                wind_mph: 3.6,
                wind_kph: 5.8,
                wind_degree: 56,
                wind_dir: "ENE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 66,
                cloud: 86,
                feelslike_c: 21.6,
                feelslike_f: 70.9,
                windchill_c: 21.6,
                windchill_f: 70.9,
                heatindex_c: 24.5,
                heatindex_f: 76.1,
                dewpoint_c: 15.1,
                dewpoint_f: 59.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.0,
                gust_kph: 6.5,
                uv: 5.0,
              },
              {
                time_epoch: 1643547600,
                time: "2022-01-30 10:00",
                temp_c: 24.4,
                temp_f: 75.9,
                is_day: 1,
                condition: {
                  text: "Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                  code: 1006,
                },
                wind_mph: 4.3,
                wind_kph: 6.8,
                wind_degree: 50,
                wind_dir: "NE",
                pressure_mb: 1011.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 57,
                cloud: 66,
                feelslike_c: 25.6,
                feelslike_f: 78.1,
                windchill_c: 24.4,
                windchill_f: 75.9,
                heatindex_c: 25.6,
                heatindex_f: 78.1,
                dewpoint_c: 15.3,
                dewpoint_f: 59.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.9,
                gust_kph: 7.9,
                uv: 5.0,
              },
              {
                time_epoch: 1643551200,
                time: "2022-01-30 11:00",
                temp_c: 25.8,
                temp_f: 78.4,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 4.0,
                wind_kph: 6.5,
                wind_degree: 42,
                wind_dir: "NE",
                pressure_mb: 1011.0,
                pressure_in: 29.84,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 54,
                cloud: 71,
                feelslike_c: 26.7,
                feelslike_f: 80.1,
                windchill_c: 25.8,
                windchill_f: 78.4,
                heatindex_c: 26.7,
                heatindex_f: 80.1,
                dewpoint_c: 15.9,
                dewpoint_f: 60.6,
                will_it_rain: 0,
                chance_of_rain: 61,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.7,
                gust_kph: 7.6,
                uv: 6.0,
              },
              {
                time_epoch: 1643554800,
                time: "2022-01-30 12:00",
                temp_c: 27.0,
                temp_f: 80.6,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 4.3,
                wind_kph: 6.8,
                wind_degree: 55,
                wind_dir: "NE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 51,
                cloud: 79,
                feelslike_c: 27.7,
                feelslike_f: 81.9,
                windchill_c: 27.0,
                windchill_f: 80.6,
                heatindex_c: 27.7,
                heatindex_f: 81.9,
                dewpoint_c: 16.0,
                dewpoint_f: 60.8,
                will_it_rain: 0,
                chance_of_rain: 70,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 5.1,
                gust_kph: 8.3,
                uv: 6.0,
              },
              {
                time_epoch: 1643558400,
                time: "2022-01-30 13:00",
                temp_c: 27.1,
                temp_f: 80.8,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 3.8,
                wind_kph: 6.1,
                wind_degree: 61,
                wind_dir: "ENE",
                pressure_mb: 1009.0,
                pressure_in: 29.79,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 50,
                cloud: 84,
                feelslike_c: 27.7,
                feelslike_f: 81.9,
                windchill_c: 27.1,
                windchill_f: 80.8,
                heatindex_c: 27.7,
                heatindex_f: 81.9,
                dewpoint_c: 15.9,
                dewpoint_f: 60.6,
                will_it_rain: 1,
                chance_of_rain: 86,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.7,
                gust_kph: 7.6,
                uv: 6.0,
              },
              {
                time_epoch: 1643562000,
                time: "2022-01-30 14:00",
                temp_c: 27.7,
                temp_f: 81.9,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 3.1,
                wind_kph: 5.0,
                wind_degree: 58,
                wind_dir: "ENE",
                pressure_mb: 1008.0,
                pressure_in: 29.77,
                precip_mm: 0.7,
                precip_in: 0.03,
                humidity: 49,
                cloud: 81,
                feelslike_c: 28.3,
                feelslike_f: 82.9,
                windchill_c: 27.7,
                windchill_f: 81.9,
                heatindex_c: 28.3,
                heatindex_f: 82.9,
                dewpoint_c: 15.9,
                dewpoint_f: 60.6,
                will_it_rain: 0,
                chance_of_rain: 60,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 9.0,
                vis_miles: 5.0,
                gust_mph: 4.0,
                gust_kph: 6.5,
                uv: 6.0,
              },
              {
                time_epoch: 1643565600,
                time: "2022-01-30 15:00",
                temp_c: 26.2,
                temp_f: 79.2,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 1.6,
                wind_kph: 2.5,
                wind_degree: 31,
                wind_dir: "NNE",
                pressure_mb: 1007.0,
                pressure_in: 29.75,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 54,
                cloud: 75,
                feelslike_c: 27.1,
                feelslike_f: 80.8,
                windchill_c: 26.2,
                windchill_f: 79.2,
                heatindex_c: 27.1,
                heatindex_f: 80.8,
                dewpoint_c: 16.3,
                dewpoint_f: 61.3,
                will_it_rain: 0,
                chance_of_rain: 61,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.2,
                gust_kph: 3.6,
                uv: 6.0,
              },
              {
                time_epoch: 1643569200,
                time: "2022-01-30 16:00",
                temp_c: 24.6,
                temp_f: 76.3,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 0.2,
                wind_kph: 0.4,
                wind_degree: 161,
                wind_dir: "SSE",
                pressure_mb: 1007.0,
                pressure_in: 29.74,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 63,
                cloud: 81,
                feelslike_c: 26.0,
                feelslike_f: 78.8,
                windchill_c: 24.6,
                windchill_f: 76.3,
                heatindex_c: 26.0,
                heatindex_f: 78.8,
                dewpoint_c: 17.2,
                dewpoint_f: 63.0,
                will_it_rain: 1,
                chance_of_rain: 88,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 0.4,
                gust_kph: 0.7,
                uv: 5.0,
              },
              {
                time_epoch: 1643572800,
                time: "2022-01-30 17:00",
                temp_c: 22.9,
                temp_f: 73.2,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 1.1,
                wind_kph: 1.8,
                wind_degree: 104,
                wind_dir: "ESE",
                pressure_mb: 1007.0,
                pressure_in: 29.75,
                precip_mm: 0.2,
                precip_in: 0.01,
                humidity: 74,
                cloud: 80,
                feelslike_c: 25.0,
                feelslike_f: 77.0,
                windchill_c: 22.9,
                windchill_f: 73.2,
                heatindex_c: 25.0,
                heatindex_f: 77.0,
                dewpoint_c: 18.0,
                dewpoint_f: 64.4,
                will_it_rain: 1,
                chance_of_rain: 81,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 9.0,
                vis_miles: 5.0,
                gust_mph: 2.0,
                gust_kph: 3.2,
                uv: 5.0,
              },
              {
                time_epoch: 1643576400,
                time: "2022-01-30 18:00",
                temp_c: 20.3,
                temp_f: 68.5,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 84,
                wind_dir: "E",
                pressure_mb: 1008.0,
                pressure_in: 29.76,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 87,
                cloud: 88,
                feelslike_c: 20.3,
                feelslike_f: 68.5,
                windchill_c: 20.3,
                windchill_f: 68.5,
                heatindex_c: 20.3,
                heatindex_f: 68.5,
                dewpoint_c: 18.1,
                dewpoint_f: 64.6,
                will_it_rain: 1,
                chance_of_rain: 71,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.8,
                gust_kph: 6.1,
                uv: 5.0,
              },
              {
                time_epoch: 1643580000,
                time: "2022-01-30 19:00",
                temp_c: 18.9,
                temp_f: 66.0,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 61,
                wind_dir: "ENE",
                pressure_mb: 1008.0,
                pressure_in: 29.77,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 92,
                cloud: 71,
                feelslike_c: 18.9,
                feelslike_f: 66.0,
                windchill_c: 18.9,
                windchill_f: 66.0,
                heatindex_c: 18.9,
                heatindex_f: 66.0,
                dewpoint_c: 17.6,
                dewpoint_f: 63.7,
                will_it_rain: 1,
                chance_of_rain: 72,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.3,
                gust_kph: 6.8,
                uv: 4.0,
              },
              {
                time_epoch: 1643583600,
                time: "2022-01-30 20:00",
                temp_c: 17.7,
                temp_f: 63.9,
                is_day: 0,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                  code: 1063,
                },
                wind_mph: 2.9,
                wind_kph: 4.7,
                wind_degree: 33,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.8,
                precip_mm: 0.5,
                precip_in: 0.02,
                humidity: 95,
                cloud: 89,
                feelslike_c: 17.7,
                feelslike_f: 63.9,
                windchill_c: 17.7,
                windchill_f: 63.9,
                heatindex_c: 17.7,
                heatindex_f: 63.9,
                dewpoint_c: 17.0,
                dewpoint_f: 62.6,
                will_it_rain: 0,
                chance_of_rain: 70,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 9.0,
                vis_miles: 5.0,
                gust_mph: 6.0,
                gust_kph: 9.7,
                uv: 1.0,
              },
              {
                time_epoch: 1643587200,
                time: "2022-01-30 21:00",
                temp_c: 17.3,
                temp_f: 63.1,
                is_day: 0,
                condition: {
                  text: "Mist",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                  code: 1030,
                },
                wind_mph: 3.8,
                wind_kph: 6.1,
                wind_degree: 30,
                wind_dir: "NNE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 97,
                cloud: 32,
                feelslike_c: 17.3,
                feelslike_f: 63.1,
                windchill_c: 17.3,
                windchill_f: 63.1,
                heatindex_c: 17.3,
                heatindex_f: 63.1,
                dewpoint_c: 16.8,
                dewpoint_f: 62.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 2.0,
                vis_miles: 1.0,
                gust_mph: 8.1,
                gust_kph: 13.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643590800,
                time: "2022-01-30 22:00",
                temp_c: 16.9,
                temp_f: 62.4,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 32,
                wind_dir: "NNE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.9,
                feelslike_f: 62.4,
                windchill_c: 16.9,
                windchill_f: 62.4,
                heatindex_c: 16.9,
                heatindex_f: 62.4,
                dewpoint_c: 16.6,
                dewpoint_f: 61.9,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 6.9,
                gust_kph: 11.2,
                uv: 1.0,
              },
              {
                time_epoch: 1643594400,
                time: "2022-01-30 23:00",
                temp_c: 16.7,
                temp_f: 62.1,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 36,
                wind_dir: "NE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.7,
                feelslike_f: 62.1,
                windchill_c: 16.7,
                windchill_f: 62.1,
                heatindex_c: 16.7,
                heatindex_f: 62.1,
                dewpoint_c: 16.4,
                dewpoint_f: 61.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 6.7,
                gust_kph: 10.8,
                uv: 1.0,
              },
            ],
          },
          {
            date: "2022-01-31",
            date_epoch: 1643587200,
            day: {
              maxtemp_c: 31.7,
              maxtemp_f: 89.1,
              mintemp_c: 16.4,
              mintemp_f: 61.5,
              avgtemp_c: 22.6,
              avgtemp_f: 72.6,
              maxwind_mph: 5.4,
              maxwind_kph: 8.6,
              totalprecip_mm: 0.2,
              totalprecip_in: 0.01,
              avgvis_km: 7.6,
              avgvis_miles: 4.0,
              avghumidity: 71.0,
              daily_will_it_rain: 1,
              daily_chance_of_rain: 84,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              uv: 11.0,
            },
            astro: {
              sunrise: "05:57 AM",
              sunset: "07:25 PM",
              moonrise: "04:56 AM",
              moonset: "07:22 PM",
              moon_phase: "Waning Crescent",
              moon_illumination: "1",
            },
            hour: [
              {
                time_epoch: 1643598000,
                time: "2022-01-31 00:00",
                temp_c: 16.4,
                temp_f: 61.5,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 29,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.81,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.4,
                feelslike_f: 61.5,
                windchill_c: 16.4,
                windchill_f: 61.5,
                heatindex_c: 16.4,
                heatindex_f: 61.5,
                dewpoint_c: 16.1,
                dewpoint_f: 61.0,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 6.7,
                gust_kph: 10.8,
                uv: 1.0,
              },
              {
                time_epoch: 1643601600,
                time: "2022-01-31 01:00",
                temp_c: 16.7,
                temp_f: 62.1,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 25,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.79,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.7,
                feelslike_f: 62.1,
                windchill_c: 16.7,
                windchill_f: 62.1,
                heatindex_c: 16.7,
                heatindex_f: 62.1,
                dewpoint_c: 16.4,
                dewpoint_f: 61.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 6.3,
                gust_kph: 10.1,
                uv: 1.0,
              },
              {
                time_epoch: 1643605200,
                time: "2022-01-31 02:00",
                temp_c: 16.6,
                temp_f: 61.9,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 25,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.78,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.6,
                feelslike_f: 61.9,
                windchill_c: 16.6,
                windchill_f: 61.9,
                heatindex_c: 16.6,
                heatindex_f: 61.9,
                dewpoint_c: 16.3,
                dewpoint_f: 61.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 6.3,
                gust_kph: 10.1,
                uv: 1.0,
              },
              {
                time_epoch: 1643608800,
                time: "2022-01-31 03:00",
                temp_c: 16.4,
                temp_f: 61.5,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 2.9,
                wind_kph: 4.7,
                wind_degree: 17,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.78,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 16.4,
                feelslike_f: 61.5,
                windchill_c: 16.4,
                windchill_f: 61.5,
                heatindex_c: 16.4,
                heatindex_f: 61.5,
                dewpoint_c: 16.1,
                dewpoint_f: 61.0,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 5.6,
                gust_kph: 9.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643612400,
                time: "2022-01-31 04:00",
                temp_c: 16.9,
                temp_f: 62.4,
                is_day: 0,
                condition: {
                  text: "Mist",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                  code: 1030,
                },
                wind_mph: 2.9,
                wind_kph: 4.7,
                wind_degree: 19,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.79,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 97,
                cloud: 49,
                feelslike_c: 16.9,
                feelslike_f: 62.4,
                windchill_c: 16.9,
                windchill_f: 62.4,
                heatindex_c: 16.9,
                heatindex_f: 62.4,
                dewpoint_c: 16.4,
                dewpoint_f: 61.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 2.0,
                vis_miles: 1.0,
                gust_mph: 5.1,
                gust_kph: 8.3,
                uv: 1.0,
              },
              {
                time_epoch: 1643616000,
                time: "2022-01-31 05:00",
                temp_c: 16.9,
                temp_f: 62.4,
                is_day: 0,
                condition: {
                  text: "Mist",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                  code: 1030,
                },
                wind_mph: 2.7,
                wind_kph: 4.3,
                wind_degree: 19,
                wind_dir: "NNE",
                pressure_mb: 1009.0,
                pressure_in: 29.8,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 95,
                cloud: 44,
                feelslike_c: 16.9,
                feelslike_f: 62.4,
                windchill_c: 16.9,
                windchill_f: 62.4,
                heatindex_c: 16.9,
                heatindex_f: 62.4,
                dewpoint_c: 16.2,
                dewpoint_f: 61.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 2.0,
                vis_miles: 1.0,
                gust_mph: 4.7,
                gust_kph: 7.6,
                uv: 1.0,
              },
              {
                time_epoch: 1643619600,
                time: "2022-01-31 06:00",
                temp_c: 17.8,
                temp_f: 64.0,
                is_day: 1,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                  code: 1003,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 27,
                wind_dir: "NNE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 92,
                cloud: 38,
                feelslike_c: 17.8,
                feelslike_f: 64.0,
                windchill_c: 17.8,
                windchill_f: 64.0,
                heatindex_c: 17.8,
                heatindex_f: 64.0,
                dewpoint_c: 16.5,
                dewpoint_f: 61.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.1,
                gust_kph: 5.0,
                uv: 5.0,
              },
              {
                time_epoch: 1643623200,
                time: "2022-01-31 07:00",
                temp_c: 20.7,
                temp_f: 69.3,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.7,
                wind_kph: 4.3,
                wind_degree: 13,
                wind_dir: "NNE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 79,
                cloud: 22,
                feelslike_c: 20.7,
                feelslike_f: 69.3,
                windchill_c: 20.7,
                windchill_f: 69.3,
                heatindex_c: 20.7,
                heatindex_f: 69.3,
                dewpoint_c: 16.9,
                dewpoint_f: 62.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.1,
                gust_kph: 5.0,
                uv: 6.0,
              },
              {
                time_epoch: 1643626800,
                time: "2022-01-31 08:00",
                temp_c: 24.4,
                temp_f: 75.9,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.5,
                wind_kph: 4.0,
                wind_degree: 333,
                wind_dir: "NNW",
                pressure_mb: 1010.0,
                pressure_in: 29.81,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 63,
                cloud: 17,
                feelslike_c: 25.8,
                feelslike_f: 78.4,
                windchill_c: 24.4,
                windchill_f: 75.9,
                heatindex_c: 25.8,
                heatindex_f: 78.4,
                dewpoint_c: 16.8,
                dewpoint_f: 62.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.9,
                gust_kph: 4.7,
                uv: 6.0,
              },
              {
                time_epoch: 1643630400,
                time: "2022-01-31 09:00",
                temp_c: 27.5,
                temp_f: 81.5,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 3.1,
                wind_kph: 5.0,
                wind_degree: 278,
                wind_dir: "W",
                pressure_mb: 1009.0,
                pressure_in: 29.8,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 51,
                cloud: 15,
                feelslike_c: 28.2,
                feelslike_f: 82.8,
                windchill_c: 27.5,
                windchill_f: 81.5,
                heatindex_c: 28.2,
                heatindex_f: 82.8,
                dewpoint_c: 16.4,
                dewpoint_f: 61.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.6,
                gust_kph: 5.8,
                uv: 7.0,
              },
              {
                time_epoch: 1643634000,
                time: "2022-01-31 10:00",
                temp_c: 29.7,
                temp_f: 85.5,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 3.6,
                wind_kph: 5.8,
                wind_degree: 261,
                wind_dir: "W",
                pressure_mb: 1008.0,
                pressure_in: 29.78,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 43,
                cloud: 21,
                feelslike_c: 30.1,
                feelslike_f: 86.2,
                windchill_c: 29.7,
                windchill_f: 85.5,
                heatindex_c: 30.1,
                heatindex_f: 86.2,
                dewpoint_c: 15.7,
                dewpoint_f: 60.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.0,
                gust_kph: 6.5,
                uv: 7.0,
              },
              {
                time_epoch: 1643637600,
                time: "2022-01-31 11:00",
                temp_c: 31.7,
                temp_f: 89.1,
                is_day: 1,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                  code: 1003,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 248,
                wind_dir: "WSW",
                pressure_mb: 1007.0,
                pressure_in: 29.75,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 36,
                cloud: 49,
                feelslike_c: 31.7,
                feelslike_f: 89.1,
                windchill_c: 31.7,
                windchill_f: 89.1,
                heatindex_c: 31.7,
                heatindex_f: 89.1,
                dewpoint_c: 14.6,
                dewpoint_f: 58.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.8,
                gust_kph: 6.1,
                uv: 8.0,
              },
              {
                time_epoch: 1643641200,
                time: "2022-01-31 12:00",
                temp_c: 30.2,
                temp_f: 86.4,
                is_day: 1,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                  code: 1003,
                },
                wind_mph: 3.6,
                wind_kph: 5.8,
                wind_degree: 241,
                wind_dir: "WSW",
                pressure_mb: 1007.0,
                pressure_in: 29.72,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 38,
                cloud: 46,
                feelslike_c: 30.1,
                feelslike_f: 86.2,
                windchill_c: 30.2,
                windchill_f: 86.4,
                heatindex_c: 30.1,
                heatindex_f: 86.2,
                dewpoint_c: 14.5,
                dewpoint_f: 58.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.0,
                gust_kph: 6.5,
                uv: 8.0,
              },
              {
                time_epoch: 1643644800,
                time: "2022-01-31 13:00",
                temp_c: 27.3,
                temp_f: 81.1,
                is_day: 1,
                condition: {
                  text: "Partly cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                  code: 1003,
                },
                wind_mph: 2.7,
                wind_kph: 4.3,
                wind_degree: 172,
                wind_dir: "S",
                pressure_mb: 1007.0,
                pressure_in: 29.72,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 52,
                cloud: 30,
                feelslike_c: 28.1,
                feelslike_f: 82.6,
                windchill_c: 27.3,
                windchill_f: 81.1,
                heatindex_c: 28.1,
                heatindex_f: 82.6,
                dewpoint_c: 16.6,
                dewpoint_f: 61.9,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.5,
                gust_kph: 7.2,
                uv: 7.0,
              },
              {
                time_epoch: 1643648400,
                time: "2022-01-31 14:00",
                temp_c: 27.7,
                temp_f: 81.9,
                is_day: 1,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                wind_mph: 4.3,
                wind_kph: 6.8,
                wind_degree: 159,
                wind_dir: "SSE",
                pressure_mb: 1006.0,
                pressure_in: 29.72,
                precip_mm: 0.2,
                precip_in: 0.01,
                humidity: 49,
                cloud: 75,
                feelslike_c: 28.3,
                feelslike_f: 82.9,
                windchill_c: 27.7,
                windchill_f: 81.9,
                heatindex_c: 28.3,
                heatindex_f: 82.9,
                dewpoint_c: 16.0,
                dewpoint_f: 60.8,
                will_it_rain: 1,
                chance_of_rain: 84,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 9.0,
                vis_miles: 5.0,
                gust_mph: 5.8,
                gust_kph: 9.4,
                uv: 6.0,
              },
              {
                time_epoch: 1643652000,
                time: "2022-01-31 15:00",
                temp_c: 30.0,
                temp_f: 86.0,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 4.7,
                wind_kph: 7.6,
                wind_degree: 124,
                wind_dir: "SE",
                pressure_mb: 1006.0,
                pressure_in: 29.7,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 43,
                cloud: 13,
                feelslike_c: 30.5,
                feelslike_f: 86.9,
                windchill_c: 30.0,
                windchill_f: 86.0,
                heatindex_c: 30.5,
                heatindex_f: 86.9,
                dewpoint_c: 16.0,
                dewpoint_f: 60.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 5.4,
                gust_kph: 8.6,
                uv: 8.0,
              },
              {
                time_epoch: 1643655600,
                time: "2022-01-31 16:00",
                temp_c: 29.0,
                temp_f: 84.2,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 5.4,
                wind_kph: 8.6,
                wind_degree: 141,
                wind_dir: "SE",
                pressure_mb: 1006.0,
                pressure_in: 29.7,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 43,
                cloud: 18,
                feelslike_c: 29.2,
                feelslike_f: 84.6,
                windchill_c: 29.0,
                windchill_f: 84.2,
                heatindex_c: 29.2,
                heatindex_f: 84.6,
                dewpoint_c: 15.2,
                dewpoint_f: 59.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 6.5,
                gust_kph: 10.4,
                uv: 7.0,
              },
              {
                time_epoch: 1643659200,
                time: "2022-01-31 17:00",
                temp_c: 27.6,
                temp_f: 81.7,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 3.6,
                wind_kph: 5.8,
                wind_degree: 124,
                wind_dir: "SE",
                pressure_mb: 1006.0,
                pressure_in: 29.7,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 49,
                cloud: 15,
                feelslike_c: 28.2,
                feelslike_f: 82.8,
                windchill_c: 27.6,
                windchill_f: 81.7,
                heatindex_c: 28.2,
                heatindex_f: 82.8,
                dewpoint_c: 15.9,
                dewpoint_f: 60.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 5.1,
                gust_kph: 8.3,
                uv: 7.0,
              },
              {
                time_epoch: 1643662800,
                time: "2022-01-31 18:00",
                temp_c: 24.1,
                temp_f: 75.4,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 77,
                wind_dir: "ENE",
                pressure_mb: 1006.0,
                pressure_in: 29.71,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 66,
                cloud: 9,
                feelslike_c: 25.7,
                feelslike_f: 78.3,
                windchill_c: 24.1,
                windchill_f: 75.4,
                heatindex_c: 25.7,
                heatindex_f: 78.3,
                dewpoint_c: 17.3,
                dewpoint_f: 63.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.3,
                gust_kph: 6.8,
                uv: 6.0,
              },
              {
                time_epoch: 1643666400,
                time: "2022-01-31 19:00",
                temp_c: 21.3,
                temp_f: 70.3,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.5,
                wind_kph: 4.0,
                wind_degree: 51,
                wind_dir: "NE",
                pressure_mb: 1007.0,
                pressure_in: 29.74,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 75,
                cloud: 7,
                feelslike_c: 21.3,
                feelslike_f: 70.3,
                windchill_c: 21.3,
                windchill_f: 70.3,
                heatindex_c: 24.4,
                heatindex_f: 75.9,
                dewpoint_c: 16.7,
                dewpoint_f: 62.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 5.1,
                gust_kph: 8.3,
                uv: 6.0,
              },
              {
                time_epoch: 1643670000,
                time: "2022-01-31 20:00",
                temp_c: 19.3,
                temp_f: 66.7,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 2.2,
                wind_kph: 3.6,
                wind_degree: 46,
                wind_dir: "NE",
                pressure_mb: 1008.0,
                pressure_in: 29.77,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 81,
                cloud: 8,
                feelslike_c: 19.3,
                feelslike_f: 66.7,
                windchill_c: 19.3,
                windchill_f: 66.7,
                heatindex_c: 19.3,
                heatindex_f: 66.7,
                dewpoint_c: 15.9,
                dewpoint_f: 60.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.7,
                gust_kph: 7.6,
                uv: 1.0,
              },
              {
                time_epoch: 1643673600,
                time: "2022-01-31 21:00",
                temp_c: 18.4,
                temp_f: 65.1,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 54,
                wind_dir: "NE",
                pressure_mb: 1009.0,
                pressure_in: 29.79,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 85,
                cloud: 7,
                feelslike_c: 18.4,
                feelslike_f: 65.1,
                windchill_c: 18.4,
                windchill_f: 65.1,
                heatindex_c: 18.4,
                heatindex_f: 65.1,
                dewpoint_c: 15.8,
                dewpoint_f: 60.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.8,
                gust_kph: 6.1,
                uv: 1.0,
              },
              {
                time_epoch: 1643677200,
                time: "2022-01-31 22:00",
                temp_c: 17.8,
                temp_f: 64.0,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 1.1,
                wind_kph: 1.8,
                wind_degree: 71,
                wind_dir: "ENE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 88,
                cloud: 6,
                feelslike_c: 17.8,
                feelslike_f: 64.0,
                windchill_c: 17.8,
                windchill_f: 64.0,
                heatindex_c: 17.8,
                heatindex_f: 64.0,
                dewpoint_c: 15.8,
                dewpoint_f: 60.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.5,
                gust_kph: 4.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643680800,
                time: "2022-01-31 23:00",
                temp_c: 17.3,
                temp_f: 63.1,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 79,
                wind_dir: "E",
                pressure_mb: 1010.0,
                pressure_in: 29.83,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 90,
                cloud: 7,
                feelslike_c: 17.3,
                feelslike_f: 63.1,
                windchill_c: 17.3,
                windchill_f: 63.1,
                heatindex_c: 17.3,
                heatindex_f: 63.1,
                dewpoint_c: 15.6,
                dewpoint_f: 60.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.8,
                gust_kph: 6.1,
                uv: 1.0,
              },
            ],
          },
          {
            date: "2022-02-01",
            date_epoch: 1643673600,
            day: {
              maxtemp_c: 35.3,
              maxtemp_f: 95.5,
              mintemp_c: 15.3,
              mintemp_f: 59.5,
              avgtemp_c: 24.3,
              avgtemp_f: 75.7,
              maxwind_mph: 7.2,
              maxwind_kph: 11.5,
              totalprecip_mm: 0.0,
              totalprecip_in: 0.0,
              avgvis_km: 8.9,
              avgvis_miles: 5.0,
              avghumidity: 64.0,
              daily_will_it_rain: 0,
              daily_chance_of_rain: 0,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              uv: 11.0,
            },
            astro: {
              sunrise: "05:58 AM",
              sunset: "07:24 PM",
              moonrise: "06:06 AM",
              moonset: "08:09 PM",
              moon_phase: "New Moon",
              moon_illumination: "0",
            },
            hour: [
              {
                time_epoch: 1643684400,
                time: "2022-02-01 00:00",
                temp_c: 16.7,
                temp_f: 62.1,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 1.3,
                wind_kph: 2.2,
                wind_degree: 71,
                wind_dir: "ENE",
                pressure_mb: 1010.0,
                pressure_in: 29.84,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 91,
                cloud: 4,
                feelslike_c: 16.7,
                feelslike_f: 62.1,
                windchill_c: 16.7,
                windchill_f: 62.1,
                heatindex_c: 16.7,
                heatindex_f: 62.1,
                dewpoint_c: 15.3,
                dewpoint_f: 59.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.9,
                gust_kph: 4.7,
                uv: 1.0,
              },
              {
                time_epoch: 1643688000,
                time: "2022-02-01 01:00",
                temp_c: 16.6,
                temp_f: 61.9,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 1.3,
                wind_kph: 2.2,
                wind_degree: 35,
                wind_dir: "NE",
                pressure_mb: 1010.0,
                pressure_in: 29.83,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 93,
                cloud: 9,
                feelslike_c: 16.6,
                feelslike_f: 61.9,
                windchill_c: 16.6,
                windchill_f: 61.9,
                heatindex_c: 16.6,
                heatindex_f: 61.9,
                dewpoint_c: 15.4,
                dewpoint_f: 59.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.9,
                gust_kph: 4.7,
                uv: 1.0,
              },
              {
                time_epoch: 1643691600,
                time: "2022-02-01 02:00",
                temp_c: 16.3,
                temp_f: 61.3,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 0.7,
                wind_kph: 1.1,
                wind_degree: 106,
                wind_dir: "ESE",
                pressure_mb: 1010.0,
                pressure_in: 29.83,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 94,
                cloud: 12,
                feelslike_c: 16.3,
                feelslike_f: 61.3,
                windchill_c: 16.3,
                windchill_f: 61.3,
                heatindex_c: 16.3,
                heatindex_f: 61.3,
                dewpoint_c: 15.3,
                dewpoint_f: 59.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 1.3,
                gust_kph: 2.2,
                uv: 1.0,
              },
              {
                time_epoch: 1643695200,
                time: "2022-02-01 03:00",
                temp_c: 15.9,
                temp_f: 60.6,
                is_day: 0,
                condition: {
                  text: "Mist",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                  code: 1030,
                },
                wind_mph: 1.3,
                wind_kph: 2.2,
                wind_degree: 128,
                wind_dir: "SE",
                pressure_mb: 1011.0,
                pressure_in: 29.84,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 96,
                cloud: 21,
                feelslike_c: 15.9,
                feelslike_f: 60.6,
                windchill_c: 15.9,
                windchill_f: 60.6,
                heatindex_c: 15.9,
                heatindex_f: 60.6,
                dewpoint_c: 15.2,
                dewpoint_f: 59.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 2.0,
                vis_miles: 1.0,
                gust_mph: 2.9,
                gust_kph: 4.7,
                uv: 1.0,
              },
              {
                time_epoch: 1643698800,
                time: "2022-02-01 04:00",
                temp_c: 15.6,
                temp_f: 60.1,
                is_day: 0,
                condition: {
                  text: "Mist",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                  code: 1030,
                },
                wind_mph: 1.3,
                wind_kph: 2.2,
                wind_degree: 123,
                wind_dir: "ESE",
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 97,
                cloud: 31,
                feelslike_c: 15.6,
                feelslike_f: 60.1,
                windchill_c: 15.6,
                windchill_f: 60.1,
                heatindex_c: 15.6,
                heatindex_f: 60.1,
                dewpoint_c: 15.1,
                dewpoint_f: 59.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 2.0,
                vis_miles: 1.0,
                gust_mph: 2.9,
                gust_kph: 4.7,
                uv: 1.0,
              },
              {
                time_epoch: 1643702400,
                time: "2022-02-01 05:00",
                temp_c: 15.3,
                temp_f: 59.5,
                is_day: 0,
                condition: {
                  text: "Fog",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                  code: 1135,
                },
                wind_mph: 1.1,
                wind_kph: 1.8,
                wind_degree: 111,
                wind_dir: "ESE",
                pressure_mb: 1012.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 98,
                cloud: 100,
                feelslike_c: 15.3,
                feelslike_f: 59.5,
                windchill_c: 15.3,
                windchill_f: 59.5,
                heatindex_c: 15.3,
                heatindex_f: 59.5,
                dewpoint_c: 14.9,
                dewpoint_f: 58.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 0.0,
                vis_miles: 0.0,
                gust_mph: 2.5,
                gust_kph: 4.0,
                uv: 1.0,
              },
              {
                time_epoch: 1643706000,
                time: "2022-02-01 06:00",
                temp_c: 17.2,
                temp_f: 63.0,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 0.9,
                wind_kph: 1.4,
                wind_degree: 113,
                wind_dir: "ESE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 89,
                cloud: 21,
                feelslike_c: 17.2,
                feelslike_f: 63.0,
                windchill_c: 17.2,
                windchill_f: 63.0,
                heatindex_c: 17.2,
                heatindex_f: 63.0,
                dewpoint_c: 15.4,
                dewpoint_f: 59.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 1.6,
                gust_kph: 2.5,
                uv: 5.0,
              },
              {
                time_epoch: 1643709600,
                time: "2022-02-01 07:00",
                temp_c: 20.9,
                temp_f: 69.6,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 1.6,
                wind_kph: 2.5,
                wind_degree: 137,
                wind_dir: "SE",
                pressure_mb: 1012.0,
                pressure_in: 29.9,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 71,
                cloud: 5,
                feelslike_c: 20.9,
                feelslike_f: 69.6,
                windchill_c: 20.9,
                windchill_f: 69.6,
                heatindex_c: 20.9,
                heatindex_f: 69.6,
                dewpoint_c: 15.5,
                dewpoint_f: 59.9,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 1.8,
                gust_kph: 2.9,
                uv: 6.0,
              },
              {
                time_epoch: 1643713200,
                time: "2022-02-01 08:00",
                temp_c: 24.2,
                temp_f: 75.6,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.2,
                wind_kph: 3.6,
                wind_degree: 136,
                wind_dir: "SE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 58,
                cloud: 5,
                feelslike_c: 25.5,
                feelslike_f: 77.9,
                windchill_c: 24.2,
                windchill_f: 75.6,
                heatindex_c: 25.5,
                heatindex_f: 77.9,
                dewpoint_c: 15.4,
                dewpoint_f: 59.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.5,
                gust_kph: 4.0,
                uv: 6.0,
              },
              {
                time_epoch: 1643716800,
                time: "2022-02-01 09:00",
                temp_c: 27.5,
                temp_f: 81.5,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.0,
                wind_kph: 3.2,
                wind_degree: 141,
                wind_dir: "SE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 47,
                cloud: 2,
                feelslike_c: 27.9,
                feelslike_f: 82.2,
                windchill_c: 27.5,
                windchill_f: 81.5,
                heatindex_c: 27.9,
                heatindex_f: 82.2,
                dewpoint_c: 15.1,
                dewpoint_f: 59.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.2,
                gust_kph: 3.6,
                uv: 7.0,
              },
              {
                time_epoch: 1643720400,
                time: "2022-02-01 10:00",
                temp_c: 30.4,
                temp_f: 86.7,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 1.8,
                wind_kph: 2.9,
                wind_degree: 171,
                wind_dir: "S",
                pressure_mb: 1011.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 38,
                cloud: 2,
                feelslike_c: 30.4,
                feelslike_f: 86.7,
                windchill_c: 30.4,
                windchill_f: 86.7,
                heatindex_c: 30.4,
                heatindex_f: 86.7,
                dewpoint_c: 14.5,
                dewpoint_f: 58.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 2.0,
                gust_kph: 3.2,
                uv: 8.0,
              },
              {
                time_epoch: 1643724000,
                time: "2022-02-01 11:00",
                temp_c: 34.2,
                temp_f: 93.6,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 2.9,
                wind_kph: 4.7,
                wind_degree: 202,
                wind_dir: "SSW",
                pressure_mb: 1011.0,
                pressure_in: 29.84,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 33,
                cloud: 4,
                feelslike_c: 34.7,
                feelslike_f: 94.5,
                windchill_c: 34.2,
                windchill_f: 93.6,
                heatindex_c: 34.7,
                heatindex_f: 94.5,
                dewpoint_c: 15.4,
                dewpoint_f: 59.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 3.4,
                gust_kph: 5.4,
                uv: 8.0,
              },
              {
                time_epoch: 1643727600,
                time: "2022-02-01 12:00",
                temp_c: 34.9,
                temp_f: 94.8,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 4.0,
                wind_kph: 6.5,
                wind_degree: 202,
                wind_dir: "SSW",
                pressure_mb: 1010.0,
                pressure_in: 29.81,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 28,
                cloud: 5,
                feelslike_c: 34.6,
                feelslike_f: 94.3,
                windchill_c: 34.9,
                windchill_f: 94.8,
                heatindex_c: 34.6,
                heatindex_f: 94.3,
                dewpoint_c: 13.5,
                dewpoint_f: 56.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.7,
                gust_kph: 7.6,
                uv: 8.0,
              },
              {
                time_epoch: 1643731200,
                time: "2022-02-01 13:00",
                temp_c: 35.3,
                temp_f: 95.5,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 4.3,
                wind_kph: 6.8,
                wind_degree: 185,
                wind_dir: "S",
                pressure_mb: 1009.0,
                pressure_in: 29.79,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 24,
                cloud: 14,
                feelslike_c: 34.5,
                feelslike_f: 94.1,
                windchill_c: 35.3,
                windchill_f: 95.5,
                heatindex_c: 34.5,
                heatindex_f: 94.1,
                dewpoint_c: 12.0,
                dewpoint_f: 53.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 4.9,
                gust_kph: 7.9,
                uv: 9.0,
              },
              {
                time_epoch: 1643734800,
                time: "2022-02-01 14:00",
                temp_c: 34.2,
                temp_f: 93.6,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 5.1,
                wind_kph: 8.3,
                wind_degree: 166,
                wind_dir: "SSE",
                pressure_mb: 1008.0,
                pressure_in: 29.77,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 24,
                cloud: 18,
                feelslike_c: 33.0,
                feelslike_f: 91.4,
                windchill_c: 34.2,
                windchill_f: 93.6,
                heatindex_c: 33.0,
                heatindex_f: 91.4,
                dewpoint_c: 11.0,
                dewpoint_f: 51.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 5.8,
                gust_kph: 9.4,
                uv: 8.0,
              },
              {
                time_epoch: 1643738400,
                time: "2022-02-01 15:00",
                temp_c: 33.4,
                temp_f: 92.1,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 6.7,
                wind_kph: 10.8,
                wind_degree: 158,
                wind_dir: "SSE",
                pressure_mb: 1008.0,
                pressure_in: 29.75,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 27,
                cloud: 15,
                feelslike_c: 32.4,
                feelslike_f: 90.3,
                windchill_c: 33.4,
                windchill_f: 92.1,
                heatindex_c: 32.4,
                heatindex_f: 90.3,
                dewpoint_c: 11.6,
                dewpoint_f: 52.9,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 7.8,
                gust_kph: 12.6,
                uv: 8.0,
              },
              {
                time_epoch: 1643742000,
                time: "2022-02-01 16:00",
                temp_c: 33.0,
                temp_f: 91.4,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 7.2,
                wind_kph: 11.5,
                wind_degree: 163,
                wind_dir: "SSE",
                pressure_mb: 1007.0,
                pressure_in: 29.75,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 32,
                cloud: 10,
                feelslike_c: 32.8,
                feelslike_f: 91.0,
                windchill_c: 33.0,
                windchill_f: 91.4,
                heatindex_c: 32.8,
                heatindex_f: 91.0,
                dewpoint_c: 14.0,
                dewpoint_f: 57.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 8.3,
                gust_kph: 13.3,
                uv: 8.0,
              },
              {
                time_epoch: 1643745600,
                time: "2022-02-01 17:00",
                temp_c: 30.6,
                temp_f: 87.1,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 6.5,
                wind_kph: 10.4,
                wind_degree: 175,
                wind_dir: "S",
                pressure_mb: 1008.0,
                pressure_in: 29.75,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 39,
                cloud: 8,
                feelslike_c: 30.8,
                feelslike_f: 87.4,
                windchill_c: 30.6,
                windchill_f: 87.1,
                heatindex_c: 30.8,
                heatindex_f: 87.4,
                dewpoint_c: 15.1,
                dewpoint_f: 59.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 7.8,
                gust_kph: 12.6,
                uv: 8.0,
              },
              {
                time_epoch: 1643749200,
                time: "2022-02-01 18:00",
                temp_c: 26.4,
                temp_f: 79.5,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 5.1,
                wind_kph: 8.3,
                wind_degree: 166,
                wind_dir: "SSE",
                pressure_mb: 1009.0,
                pressure_in: 29.78,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 53,
                cloud: 7,
                feelslike_c: 27.2,
                feelslike_f: 81.0,
                windchill_c: 26.4,
                windchill_f: 79.5,
                heatindex_c: 27.2,
                heatindex_f: 81.0,
                dewpoint_c: 16.1,
                dewpoint_f: 61.0,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.2,
                gust_kph: 14.8,
                uv: 7.0,
              },
              {
                time_epoch: 1643752800,
                time: "2022-02-01 19:00",
                temp_c: 24.0,
                temp_f: 75.2,
                is_day: 1,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                wind_mph: 4.7,
                wind_kph: 7.6,
                wind_degree: 133,
                wind_dir: "SE",
                pressure_mb: 1010.0,
                pressure_in: 29.82,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 67,
                cloud: 5,
                feelslike_c: 25.6,
                feelslike_f: 78.1,
                windchill_c: 24.0,
                windchill_f: 75.2,
                heatindex_c: 25.6,
                heatindex_f: 78.1,
                dewpoint_c: 17.6,
                dewpoint_f: 63.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 8.3,
                gust_kph: 13.3,
                uv: 6.0,
              },
              {
                time_epoch: 1643756400,
                time: "2022-02-01 20:00",
                temp_c: 21.2,
                temp_f: 70.2,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 3.6,
                wind_kph: 5.8,
                wind_degree: 120,
                wind_dir: "ESE",
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 81,
                cloud: 4,
                feelslike_c: 21.2,
                feelslike_f: 70.2,
                windchill_c: 21.2,
                windchill_f: 70.2,
                heatindex_c: 24.3,
                heatindex_f: 75.7,
                dewpoint_c: 17.9,
                dewpoint_f: 64.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 7.4,
                gust_kph: 11.9,
                uv: 1.0,
              },
              {
                time_epoch: 1643760000,
                time: "2022-02-01 21:00",
                temp_c: 20.4,
                temp_f: 68.7,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 3.4,
                wind_kph: 5.4,
                wind_degree: 103,
                wind_dir: "ESE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 87,
                cloud: 3,
                feelslike_c: 20.4,
                feelslike_f: 68.7,
                windchill_c: 20.4,
                windchill_f: 68.7,
                heatindex_c: 20.4,
                heatindex_f: 68.7,
                dewpoint_c: 18.2,
                dewpoint_f: 64.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 6.7,
                gust_kph: 10.8,
                uv: 1.0,
              },
              {
                time_epoch: 1643763600,
                time: "2022-02-01 22:00",
                temp_c: 19.7,
                temp_f: 67.5,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 3.1,
                wind_kph: 5.0,
                wind_degree: 77,
                wind_dir: "ENE",
                pressure_mb: 1012.0,
                pressure_in: 29.9,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 90,
                cloud: 3,
                feelslike_c: 19.7,
                feelslike_f: 67.5,
                windchill_c: 19.7,
                windchill_f: 67.5,
                heatindex_c: 19.7,
                heatindex_f: 67.5,
                dewpoint_c: 18.0,
                dewpoint_f: 64.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 6.3,
                gust_kph: 10.1,
                uv: 1.0,
              },
              {
                time_epoch: 1643767200,
                time: "2022-02-01 23:00",
                temp_c: 19.2,
                temp_f: 66.6,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000,
                },
                wind_mph: 3.1,
                wind_kph: 5.0,
                wind_degree: 62,
                wind_dir: "ENE",
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 91,
                cloud: 4,
                feelslike_c: 19.2,
                feelslike_f: 66.6,
                windchill_c: 19.2,
                windchill_f: 66.6,
                heatindex_c: 19.2,
                heatindex_f: 66.6,
                dewpoint_c: 17.6,
                dewpoint_f: 63.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 6.5,
                gust_kph: 10.4,
                uv: 1.0,
              },
            ],
          },
        ],
      },
      alerts: {
        alert: [],
      },
    },
  };
};

export default Home;
